name: serenity_dart_compat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.8.0
  rust_lib_serenity_dart_compat:
    path: rust_builder
  freezed_annotation: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  freezed: ^3.0.3
  build_runner: ^2.4.15
  

flutter:
  uses-material-design: true
